site_name: pyDB
site_description: ''
site_author: 'nakano16180'

# Copyright
copyright: 'Copyright (c) 2020'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  palette:
    primary: 'Light Blue'
    accent: 'Orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'

# Extensions
markdown_extensions:
  - codehilite:
  - admonition:
  - toc:
      permalink: '#'
